8hachi8/fleamarket_sample_78h

Gemfile

プルリクエスト作成テスト
チーム開発で正常にプルリクエストが作成できるか確認のため

test_kajiki

---

Gemfile

my_first_commit

---

Gemfile

プルリクエスト作成テスト
問題なくマスターブランチを変更できるように確認するため

test_merge

---

Gemfile

my_second_commit

---

Gemfile

test_kaji2

---

README.md

READMEへのDBの記述を行なった。
※ER図リンク
↓
https://app.lucidchart.com/invitations/accept/b31c1bff-5f7f-486f-b79a-e5e1b124f937 
DB設計のための設計図準備のため。

[WIP] READMEへのDB記述

---

Capfile
Gemfile
Gemfile.lock
app/assets/stylesheets/items.scss
app/controllers/items_controller.rb
app/helpers/items_helper.rb
app/views/items/index.html.haml
config/database.yml
config/deploy.rb
config/deploy/production.rb
config/deploy/staging.rb
config/routes.rb
config/unicorn.rb
test/controllers/items_controller_test.rb

デプロイ作業のためブランチを作成した。
本番環境にwebアプリをupするため。

[WIP]Deployment operation

---

README.md
app/models/profile.rb
app/models/shipping_address.rb
app/models/user.rb
config/initializers/devise.rb
config/locales/devise.en.yml
config/routes.rb
db/migrate/20200701024018_devise_create_users.rb
db/migrate/20200701074712_create_profiles.rb
db/migrate/20200701082917_create_shipping_addresses.rb
db/schema.rb
test/fixtures/profiles.yml
test/fixtures/shipping_addresses.yml
test/fixtures/users.yml
test/models/profile_test.rb
test/models/shipping_address_test.rb
test/models/user_test.rb

下記3つのテーブルを作成した。
Users、Profiles、Shipping_addressesテーブル。
各migrationファイルとmodelファイルへの記述を確認願いたい。
今後、ルーティング、コントローラー、ビューの実装を進めるための下準備。

[WIP] users、profiles、shipping_addressesテーブルの作成

---

app/views/homes/_footer.html.haml
app/views/homes/_header.html.haml
app/views/homes/index.html.haml
app/views/items/show.html.haml

本番環境の画像ファイルの表示場所を変更した。
今までの状態だと本番環境での画像が表示されないため。

Change images location

---

app/views/users/show.html.haml

マイページに"出品ボタン"を追加した。
部分テンプレートで用意しているものをrenderで呼び出している。
必要な機能のため。

"出品ボタン"の追加

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/modules/homes/category-tree.scss
app/assets/stylesheets/modules/homes/header.scss
app/controllers/categories_controller.rb
app/controllers/homes_controller.rb
app/controllers/items_controller.rb
app/controllers/users_controller.rb
app/views/homes/_category-tree.html.haml
app/views/homes/_header.html.haml

ヘッダー内のドロップダウンメニュー機能の実装
カテゴリーは多重構造となっており、最小限のページで各カテゴリーページへリンクするため

add_category_tree

---

app/views/devise/registrations/edit.html.haml
app/views/profiles/_footer.html.haml
app/views/profiles/_header.html.haml
app/views/profiles/edit.html.haml
app/views/profiles/new.html.haml

本番環境用に画像を表示できるように一部画像ファイルパスを修正した。
本番環境で画像が表示されなければ利用者に迷惑をかけるので。

Fix production image

---

app/assets/javascripts/application.js
app/assets/javascripts/new_item.js
app/assets/stylesheets/modules/items/new.scss
app/controllers/homes_controller.rb
app/views/homes/_sell-btn.html.haml
app/views/homes/index.html.haml
app/views/items/new.html.haml

出品画面上の画像プレビュー機能
アップロードする画像を出品前に確認する機能が必要となるため
出品機能は前もって実装済みとなっています。
バリデーションに関しては今回もテストを行い、出品機能実装時と同じ仕様を維持できていることを確認済みです。

[WIP]add_image_preview_in_sell_page

---

app/controllers/application_controller.rb

表題の通り、ログアウト時でも商品詳細ページは見れるように実装した。
ユーザー登録しなくても商品詳細の確認権限はあってもいいから。
https://gyazo.com/71bed323318554c428d7819c346ccd77
シンプルすぎる仕様変更ですが、他にいいやり方があれば教えてください。
items_controllerのshowに直接書き込むやり方とか🤗

[WIP]商品詳細ページ、ログアウト時でも閲覧可

---

README.md
app/controllers/profiles_controller.rb
app/views/shipping_address/edit.html.haml
app/views/shipping_address/new.html.haml
db/migrate/20200716092627_change_datatype_postal_code_of_shipping_addresses.rb
db/schema.rb

軽微な修正を行った
・郵便番号のデータの型をintegerからstringへ
・プロフィール画面遷移時の挙動をrenderからredirect_toへ
郵便番号は0から始まった場合、integerでは0落ちする恐れがあるため

fix_redirect_page_and_datatype

---

app/assets/stylesheets/modules/items/show.scss
app/views/items/show.html.haml

表題の通り、商品詳細ページにてコメントできるようマークアップ を作成した。
商品の購入前にある程度商品に関しての質問ができるようにした方が利用者にとって不明点の解消などになるだろうから。
https://gyazo.com/7731e76e936fed6958f2a0f0ce49f345
必須の進捗に応じてサーバサイドを考慮する。

[WIP]商品についての質問・コメント機能[マークアップ ]

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/modules/purchase/done.scss
app/controllers/purchase_controller.rb
app/views/purchase/done.html.haml
config/routes.rb

購入後ページの実装
商品購入後、取引きが成立したことを通知する必要があるため

add_buy_result_page

---

app/assets/stylesheets/modules/credit_cards/show.scss
app/assets/stylesheets/modules/items/show.scss
app/assets/stylesheets/modules/purchase/show.scss
app/assets/stylesheets/modules/users/show.scss
app/controllers/purchase_controller.rb
app/views/credit_cards/show.html.haml
app/views/purchase/show.html.haml
app/views/users/show.html.haml
config/application.rb
config/routes.rb

下記6点の変更、修正を行なった。
・商品購入完了後に『doneページ』に遷移
・日時を日本(東京)時間に変更
・商品詳細ページの『購入画面に進む』ボタンの仕様変更
・購入確認ページの『購入する』ボタンの仕様変更
・マイページのアバター欄にログインユーザーのニックネームを表示
・クレジットカード情報削除ページの『削除する』ボタンの仕様変更
UI向上のため。

[WIP] 細部の修正

---

app/assets/javascripts/category.js

カテゴリー機能の修正
商品編集画面でjsがうまく作動しなかったため

[WIP]add_fixed_category_function

---

app/assets/stylesheets/modules/_flash.scss
app/controllers/items_controller.rb
app/views/items/edit.html.haml

出品/商品編集画面の入力エラー時の挙動変更
画像アップロード機能の挙動確保のため

[WIP]fixed_category_alert

---

app/controllers/users_controller.rb
app/views/devise/registrations/edit.html.haml
config/routes.rb

アカウント編集がエラーになっていたので修正を行なった。
下記3点を修正した
↓
・ルーティング
・コントローラー
・ビューファイル
エラー解決のため

『アカウント編集』機能の修正

---

app/assets/stylesheets/modules/items/new.scss
app/assets/stylesheets/modules/items/show.scss
app/controllers/items_controller.rb
app/views/items/edit.html.haml
app/views/items/new.html.haml
app/views/items/show.html.haml

商品出品時と商品編集時の画面遷移、メッセージなど変更した。
利用者の操作性を考慮したため。

Fix item css&ss

---

app/controllers/users_controller.rb

『アカウント編集』後のリダイレクト先をトップページからマイページに変更
利便性向上のため

リダイレクト先の変更
